---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      k8s:
        patterns: [ "k8s.io/*", "sigs.k8s.io/*" ]
        update-types: [ "major", "minor", "patch" ]
      redhat-best-practices-for-k8s:
        patterns: [ "github.com/redhat-best-practices-for-k8s/*" ]
        update-types: [ "major", "minor", "patch" ]
      openshift:
        patterns: [ "github.com/openshift/*" ]
        update-types: [ "major", "minor", "patch" ]
      other-go-modules:
        patterns: [ "*" ]
        exclude-patterns: 
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/redhat-best-practices-for-k8s/*"
          - "github.com/openshift/*"
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-images:
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: [ "actions/*" ]
        update-types: [ "major", "minor", "patch" ]
      docker: 
        patterns: [ "docker/*" ]
        update-types: [ "major", "minor", "patch" ]
      other-actions:
        patterns: [ "*" ]
        exclude-patterns: 
          - "actions/*"
          - "docker/*"
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: github-actions
    directory: /.github/actions/setup-partner-cluster
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: [ "actions/*" ]
        update-types: [ "major", "minor", "patch" ]
      docker: 
        patterns: [ "docker/*" ]
        update-types: [ "major", "minor", "patch" ]
      other-actions:
        patterns: [ "*" ]
        exclude-patterns: 
          - "actions/*"
          - "docker/*"
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: github-actions
    directory: /.github/actions/setup
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: [ "actions/*" ]
        update-types: [ "major", "minor", "patch" ]
      docker: 
        patterns: [ "docker/*" ]
        update-types: [ "major", "minor", "patch" ]
      other-actions:
        patterns: [ "*" ]
        exclude-patterns: 
          - "actions/*"
          - "docker/*"
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: docker
    directory: /.github/actions/documentation
    schedule:
      interval: weekly
    groups:
      docker-images:
        update-types: [ "major", "minor", "patch" ]
