---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      k8s:
        patterns: [ "k8s.io/*", "sigs.k8s.io/*" ]
        update-types: [ "major", "minor", "patch" ]
      redhat-best-practices-for-k8s:
        patterns: [ "github.com/redhat-best-practices-for-k8s/*" ]
        update-types: [ "major", "minor", "patch" ]
      openshift:
        patterns: [ "github.com/openshift/*" ]
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      ubi9:
        patterns: [ "registry.access.redhat.com/ubi9/*" ]
        update-types: [ "major", "minor", "patch" ]
      ubi8:
        patterns: [ "registry.access.redhat.com/ubi8/*" ]
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: [ "actions/*" ]
        update-types: [ "major", "minor", "patch" ]
      docker: 
        patterns: [ "docker/*" ]
        update-types: [ "major", "minor", "patch" ]
      ci-runtime:
        patterns: [ "*quick-*" ]
        update-types: [ "major", "minor", "patch" ]
  - package-ecosystem: docker
    directory: /.github/actions/documentation
    schedule:
      interval: weekly
    groups:
      docs-ubi:
        patterns: [ "registry.access.redhat.com/ubi9/*" ]
        update-types: [ "major", "minor", "patch" ]
      docs-ubi8:  
        patterns: [ "registry.access.redhat.com/ubi8/*" ]
        update-types: [ "major", "minor", "patch" ]
