linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 60
    statements: 45
  goconst:
    min-len: 4
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
    settings: 
      tooManyResultsChecker:
        # Maximum number of results.
        # Default: 5
        maxResults: 10
  gocyclo:
    min-complexity: 20
  govet:
    disable:
      - printf
  gosec:
    excludes: 
      - G115
  lll:
    line-length: 250
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # do not require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  exhaustive:
    default-signifies-exhaustive: true
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - copyloopvar
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  # do not enable:
  # - asciicheck
  # - depguard
  # - dupl
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - maligned
  # - nakedret
  # - nestif
  # - noctx
  # - prealloc
  # - revive
  # - copyloopvar
  # - testpackage
  # - wsl
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Ignore magic numbers, inline strings and function length in tests.
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - funlen
    - path: config/config.go
      linters:
        - mnd
    - path: _scaling.go
      linters:
        - gocritic
    - path: hugepages.go
      linters:
        - mnd
    - path: scheduling.go
      linters:
        - mnd
    # Ignore line length for string assignments (do not try and wrap regex definitions)
    - linters:
        - lll
      source: "^(.*= (\".*\"|`.*`))$"
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    # Ignore static strings in tests
