---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scenario-account
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automount-enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automount-enabled
      scenario-automount: target
  template:
    metadata:
      labels:
        app: automount-enabled
        scenario-automount: target
    spec:
      serviceAccountName: scenario-account
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27
