name: 'Setup Docker Storage'
description: 'Configures Docker to use /mnt/docker-storage instead of /var/lib/docker'
runs:
  using: "composite"
  steps:
    - name: Create docker/daemon.json if it does not exist
      shell: bash
      run: |
        if [ ! -f /etc/docker/daemon.json ]; then
          echo '{}' | sudo tee /etc/docker/daemon.json
        fi

    - name: Make docker to use /mnt (sdb) for storage
      shell: bash
      run: |
        df -h
        lsblk
        sudo mkdir /mnt/docker-storage
        sudo jq '.  +={"data-root" : "/mnt/docker-storage"}' < /etc/docker/daemon.json > /tmp/docker-daemon.json
        sudo cp /tmp/docker-daemon.json /etc/docker/daemon.json
        cat /etc/docker/daemon.json
        sudo systemctl restart docker
        sudo ls -la /mnt/docker-storage

