---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-name-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-name-http
      scenario-container: target
  template:
    metadata:
      labels:
        app: port-name-http
        scenario-container: target
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27
          ports:
            - name: http
              containerPort: 8080
