name: Test Incoming Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  REGISTRY: quay.io
  REGISTRY_LOCAL: localhost
  IMAGE_NAME: testnetworkfunction/test-network-function
  IMAGE_TAG: unstable
  TNF_CONTAINER_CLIENT: docker
  TNF_NON_INTRUSIVE_ONLY: false
  TNF_DISABLE_CONFIG_AUTODISCOVER: false
  TNF_CONFIG_DIR: /tmp/tnf/config
  TNF_OUTPUT_DIR: /tmp/tnf/output
  TNF_SRC_URL: 'https://github.com/${{ github.repository }}'
  TESTING_CMD_PARAMS: '-n host -i ${REGISTRY_LOCAL}/${IMAGE_NAME}:${IMAGE_TAG} -t ${TNF_CONFIG_DIR} -o ${TNF_OUTPUT_DIR}'
  TNF_PARTNER_DIR: '/usr/tnf-partner'
  TNF_PARTNER_SRC_DIR: '${TNF_PARTNER_DIR}/src'

jobs:
  lint:
    name: Run Linter and Vet
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Rebuild mocks
        run: go install github.com/golang/mock/mockgen@v1.6.0 && make mocks

      # TODO: golangci-lint team recommends using a GitHub Action to perform golangci-lint responsibilities.  However
      # there does not appear to be a way to honor our existing .golangci.yml.  For now, mimic developer behavior.
      - name: Install golangci-lint
        run: make install-lint

      - name: make lint
        run: make lint

      - name: make vet
        run: make vet

  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                level: warning
              trailing-spaces:
                level: warning
              brackets:
                level: warning
              empty-lines:
                level: warning

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Rebuild mocks
        run: go install github.com/golang/mock/mockgen@v1.6.0 && make mocks

      - name: Run Tests
        run: make test
        env:
          SHELL: /bin/bash

  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-20.04
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/runner/.kube/config'

    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Execute `make mocks`
        run: go install github.com/golang/mock/mockgen@v1.6.0 && make mocks

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo@v1.16.5

      - name: Execute `make build`
        run: make build

      # Create a minikube cluster for testing.

      - name: Check out `cnf-certification-test-partner`
        uses: actions/checkout@v2
        with:
          repository: test-network-function/cnf-certification-test-partner
          path: cnf-certification-test-partner

      - name: Start the minikube cluster for `local-test-infra`
        uses: ./cnf-certification-test-partner/.github/actions/start-minikube
        with:
          working_directory: cnf-certification-test-partner

      - name: Create `local-test-infra` OpenShift resources
        uses: ./cnf-certification-test-partner/.github/actions/create-local-test-infra-resources
        with:
          working_directory: cnf-certification-test-partner

      # Perform smoke tests.

      - name: 'Test: Run test suites'
        run: ./run-cnf-suites.sh --focus access-control diagnostic lifecycle platform observablility networking affiliated-certification operator

      - name: Upload smoke test results as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: smoke-tests
          path: |
            test-network-function/*.xml
            test-network-function/claim.json
            test-network-function/claimjson.js
            test-network-function/results.html

      # Perform smoke tests using a TNF container.

      - name: Build the `test-network-function` image
        run: |
          docker build --no-cache \
            -t ${REGISTRY_LOCAL}/${IMAGE_NAME}:${IMAGE_TAG} \
            -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} \
            --build-arg TNF_VERSION=${COMMIT_SHA} \
            --build-arg TNF_SRC_URL=${TNF_SRC_URL} .
        env:
          COMMIT_SHA: ${{ github.sha }}

      - name: Create required TNF config files and directories
        run: |
          mkdir -p $TNF_CONFIG_DIR $TNF_OUTPUT_DIR
          cp test-network-function/*.yml $TNF_CONFIG_DIR
        shell: bash

      - name: 'Test: Run diagnostic test suite in a TNF container'
        run: ./run-tnf-container.sh ${{ env.TESTING_CMD_PARAMS }} -f diagnostic

      - name: Delete the deployment and deploy Statefulset pods
        uses: ./cnf-certification-test-partner/.github/actions/deploy-statefulset-pods
        with:
          working_directory: cnf-certification-test-partner
          
      - name: 'Test: Run generic test suite in a TNF container'
        run: ./run-tnf-container.sh ${{ env.TESTING_CMD_PARAMS }} -f access-control lifecycle platform observablility networking affiliated-certification operator

      - name: Upload container test results as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: smoke-tests-container
          path: |
            ${{ env.TNF_OUTPUT_DIR }}/*.xml
            ${{ env.TNF_OUTPUT_DIR }}/claim.json
            ${{ env.TNF_OUTPUT_DIR }}/claimjson.js
            ${{ env.TNF_OUTPUT_DIR }}/results.html

      # Push the new unstable TNF image to Quay.io.
      - name: (if on main and upstream) Authenticate against Quay.io
        if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'test-network-function' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: (if on main and upstream) Push the newly built image to Quay.io
        if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'test-network-function' }}
        run: docker push --all-tags ${REGISTRY}/${IMAGE_NAME}
