name: 'Free Disk Space'
description: 'Frees up disk space on Ubuntu runners by removing unnecessary packages and files'
runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        large-packages: true
        android: true
        dotnet: true
        haskell: true
        docker-images: true
        swap-storage: false
      shell: bash

