name: setup-partner-cluster
description: 'Setup a partner cluster for testing.'

inputs:
  make-command:
    description: 'The make command to run.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out `certsuite-sample-workload`
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: redhat-best-practices-for-k8s/certsuite-sample-workload
        path: certsuite-sample-workload

    - name: Setup quick-k8s cluster
      uses: palmsoftware/quick-k8s@v0.0.43
      with:
        disableDefaultCni: true
        numControlPlaneNodes: 1
        numWorkerNodes: 2
        installOLM: true
        removeDefaultStorageClass: true
        removeControlPlaneTaint: true

    - name: Run 'make ${{inputs.make-command}}'
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
      with:
        timeout_minutes: 150
        max_attempts: 3
        command: cd ${GITHUB_WORKSPACE}/certsuite-sample-workload; python3 -m venv .venv; source .venv/bin/activate; pip install --upgrade pip; pip install jinjanator; cp .venv/bin/jinjanate .venv/bin/j2; make ${{ inputs.make-command }}

    - name: Show pods
      shell: bash
      run: oc get pods -A
