name: QE OCP 4.20 Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at midnight UTC
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  qe-ocp-420:
    uses: ./.github/workflows/_qe-ocp-crc.yaml
    with:
      ocp-version: '4.20'
      ocp-version-slug: '420'
      intrusive: false
      suites: '["affiliatedcertification-ocp", "performance-ocp", "platformalteration1-ocp", "platformalteration2-ocp", "platformalteration3-ocp", "platformalteration4-ocp"]'
    secrets:
      CRC_PULL_SECRET: ${{ secrets.CRC_PULL_SECRET }}
      QE_NIGHTLY_WEBHOOK: ${{ secrets.QE_NIGHTLY_WEBHOOK }}
