name: QE OCP 4.16 Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at midnight UTC
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  qe-ocp-416:
    uses: ./.github/workflows/_qe-ocp-selfhosted.yaml
    with:
      ocp-version: '4.16'
      ocp-version-slug: '416'
      runner-label: 'qe-ocp-416'
      lab-user: 'labuser3'
      intrusive: false
      suites: '["affiliatedcertification-ocp", "performance-ocp", "platformalteration1-ocp", "platformalteration2-ocp", "platformalteration3-ocp", "platformalteration4-ocp"]'
    secrets:
      QE_NIGHTLY_WEBHOOK: ${{ secrets.QE_NIGHTLY_WEBHOOK }}
