name: QE OCP 4.16 Intrusive Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at 5 UTC
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: read

jobs:
  qe-ocp-416-intrusive:
    uses: ./.github/workflows/_qe-ocp-selfhosted.yaml
    with:
      ocp-version: '4.16'
      ocp-version-slug: '416'
      runner-label: 'qe-ocp-416'
      lab-user: 'labuser3'
      intrusive: true
      suites: '["lifecycle"]'
      job-timeout: 300
      test-timeout: 180
    secrets:
      QE_NIGHTLY_WEBHOOK: ${{ secrets.QE_NIGHTLY_WEBHOOK }}
