name: QE OCP 4.14 Intrusive Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at midnight UTC
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  qe-ocp-414-intrusive:
    uses: ./.github/workflows/_qe-ocp-selfhosted.yaml
    with:
      ocp-version: '4.14'
      ocp-version-slug: '414'
      runner-label: 'qe-ocp-414'
      lab-user: 'labuser2'
      intrusive: true
      suites: '["lifecycle"]'
      job-timeout: 300
      test-timeout: 180
    secrets:
      QE_NIGHTLY_WEBHOOK: ${{ secrets.QE_NIGHTLY_WEBHOOK }}
