name: QE OCP 4.22 Intrusive Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at midnight UTC
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  qe-ocp-422-intrusive:
    uses: ./.github/workflows/_qe-ocp-crc.yaml
    with:
      ocp-version: '4.22'
      ocp-version-slug: '422'
      intrusive: true
      suites: '["lifecycle"]'
      job-timeout: 300
      test-timeout: 180
    secrets:
      CRC_PULL_SECRET: ${{ secrets.CRC_PULL_SECRET }}
      QE_NIGHTLY_WEBHOOK: ${{ secrets.QE_NIGHTLY_WEBHOOK }}
