name: QE OCP 4.15 Intrusive Testing

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  # Schedule a daily cron at 5 UTC
  schedule:
    - cron: '0 5 * * *'
env:
  QE_REPO: test-network-function/cnfcert-tests-verification

jobs:
  pull-unstable-image:
    runs-on: qe-ocp
    env:
      SHELL: /bin/bash
      FORCE_DOWNLOAD_UNSTABLE: true
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: ${{ github.sha }}

      - name: Clone the QE repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          repository: ${{ env.QE_REPO }}
          path: cnfcert-tests-verification

      - name: Run the script to pull the unstable image
        run: ./scripts/download-unstable.sh
        working-directory: cnfcert-tests-verification

  qe-ocp-415-intrusive-testing:
    runs-on: qe-ocp
    needs: pull-unstable-image
    if: needs.pull-unstable-image.result == 'success'
    strategy:
      fail-fast: false
      matrix: 
        # Add more suites if more intrusive tests are added to the QE repo
        suite: [lifecycle]
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/home/labuser/.kube/config'
      PFLT_DOCKERCONFIG: '/home/labuser/.docker/config'
      TEST_TNF_IMAGE_NAME: quay.io/testnetworkfunction/cnf-certification-test
      TEST_TNF_IMAGE_TAG: unstable
      DOCKER_CONFIG_DIR: '/home/labuser/.docker'
      TNF_CONFIG_DIR: '/home/labuser/tnf_config'
      TNF_REPORT_DIR: '/home/labuser/tnf_report'

    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          ref: ${{ github.sha }}

      - name: Run initial setup
        uses: ./.github/actions/setup

      - name: Show pods
        run: oc get pods -A

      - name: Clone the QE repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          repository: ${{ env.QE_REPO }}
          path: cnfcert-tests-verification

      - name: Preemptively potential QE namespaces
        run: ./scripts/delete-namespaces.sh
        working-directory: cnfcert-tests-verification

      - name: Preemptively delete contents of openshift-marketplace namespace
        run: ./scripts/clean-marketplace.sh
        working-directory: cnfcert-tests-verification

      - name: Preemptively delete report and config folders
        shell: bash
        run: |
          sudo rm -rf ${{env.TNF_CONFIG_DIR}}
          sudo rm -rf ${{env.TNF_REPORT_DIR}}

      - name: Run the tests
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: cd ${GITHUB_WORKSPACE}/cnfcert-tests-verification; FEATURES=${{matrix.suite}} TNF_REPO_PATH=${GITHUB_WORKSPACE} TNF_IMAGE=${{env.TEST_TNF_IMAGE_NAME}} TNF_IMAGE_TAG=${{env.TEST_TNF_IMAGE_TAG}} JOB_ID=${{github.run_id}} DISABLE_INTRUSIVE_TESTS=false ENABLE_PARALLEL=true ENABLE_FLAKY_RETRY=true make test-features 

      - name: (if on main and upstream) Send chat msg to dev team if failed to run QE tests
        if: ${{ failure() && github.ref == 'refs/heads/main' && github.repository_owner == 'test-network-function' }}
        env:
          COMMIT_SHA: ${{ github.sha }}
          JOB_RUN_ID: ${{ github.run_id }}
          JOB_RUN_ATTEMPT: ${{ github.run_attempt }}
          GITHUB_REPO: https://github.com/test-network-function/cnf-certification-test
        run: |
          curl -X POST --data "{
              \"text\": \"🚨⚠️  Failed to run intrusive OCP 4.15 QE tests from commit \<$GITHUB_REPO/commit/$COMMIT_SHA|$COMMIT_SHA\>, job ID \<$GITHUB_REPO/actions/runs/$JOB_RUN_ID/attempts/$JOB_RUN_ATTEMPT|$JOB_RUN_ID\> \"
          }" -H 'Content-type: application/json; charset=UTF-8' '${{ secrets.QE_NIGHTLY_WEBHOOK }}'
