// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientsholder

import (
	"sync"
)

// Ensure, that CommandMock does implement Command.
// If this is not the case, regenerate this file with moq.
var _ Command = &CommandMock{}

// CommandMock is a mock implementation of the Command interface used in tests to simulate command execution behavior.
//
// It contains a function field ExecCommandContainerFunc that can be set to provide custom logic when ExecCommandContainer is called. Each call is recorded with its context and string argument, allowing test code to inspect invocation history via ExecCommandContainerCalls. The struct uses an RWMutex to guard concurrent access to the calls slice.
type CommandMock struct {
	// ExecCommandContainerFunc mocks the ExecCommandContainer method.
	ExecCommandContainerFunc func(context Context, s string) (string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ExecCommandContainer holds details about calls to the ExecCommandContainer method.
		ExecCommandContainer []struct {
			// Context is the context argument value.
			Context Context
			// S is the s argument value.
			S string
		}
	}
	lockExecCommandContainer sync.RWMutex
}

// ExecCommandContainer executes a command inside a container and returns its output, error output, and any execution error.
//
// It takes a context for cancellation or timeout, and the command string to run.
// The function is part of a mock implementation; it forwards the call to ExecCommandContainerFunc
// after acquiring a lock to protect shared state. The returned values are the standard output,
// standard error, and an error if the execution failed.
func (mock *CommandMock) ExecCommandContainer(context Context, s string) (string, string, error) {
	if mock.ExecCommandContainerFunc == nil {
		panic("CommandMock.ExecCommandContainerFunc: method is nil but Command.ExecCommandContainer was just called")
	}
	callInfo := struct {
		Context Context
		S       string
	}{
		Context: context,
		S:       s,
	}
	mock.lockExecCommandContainer.Lock()
	mock.calls.ExecCommandContainer = append(mock.calls.ExecCommandContainer, callInfo)
	mock.lockExecCommandContainer.Unlock()
	return mock.ExecCommandContainerFunc(context, s)
}

// ExecCommandContainerCalls returns all recorded calls to ExecCommandContainer.
//
// It retrieves a slice of structs, each containing the execution context and the command string that was passed
// when ExecCommandContainer was invoked on the mock. The returned slice can be examined to verify how many times
// the method was called and with what parameters. Use len(mock.ExecCommandContainerCalls()) to check the number of calls.
func (mock *CommandMock) ExecCommandContainerCalls() []struct {
	Context Context
	S       string
} {
	var calls []struct {
		Context Context
		S       string
	}
	mock.lockExecCommandContainer.RLock()
	calls = mock.calls.ExecCommandContainer
	mock.lockExecCommandContainer.RUnlock()
	return calls
}
